name: Beginner CI

on:
  push:
    branches:
      - main

jobs:
  check-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Repository Files
        run: ls -la

      - name: Verify index.html Exists
        run: test -f index.html

      - name: Success Message
        run: echo "Beginner CI Pipeline Passed"